### ISSUE TITLE
Topic suggestion: Promises

### ISSUE THREAD

**Issue by jainaayush05** [jadjoubran/codetogo.io#1]
Promises

**Comment by jadjoubran** [comment]
Awesome topic!
I'm thinking about these 2 use cases:

- How to create a promise in JavaScript
- How to resolve a promise in JavaScript
- How to reject a promise in JavaScript

do you have any other use case suggestions? 😄

**Comment by jainaayush05** [comment]
These three sounds good for the starters. Best,Aayush

**Comment by politologu** [comment]
Yep :)

**Comment by politologu** [comment]
Which is the difference between var, let and cons?

**Comment by politologu** [comment]
Use Case Suggestion: how to call a function in javascript

**Comment by jadjoubran** [comment]
🎬 [How to create a promise in JavaScript](https://codetogo.io/how-to-create-a-promise-in-javascript/)
