### ISSUE TITLE
Use Case Suggestion: count number of tables

### ISSUE THREAD

**Issue by adela13** [jadjoubran/codetogo.io#102]

**Comment by jadjoubran** [comment]
Thanks @adela13! 😄 
I will add a use case by making this a little bit more generic as it applies to any element that you can find through `querySelectorAll`

**Comment by jadjoubran** [comment]
🎬 [How to get count of DOM elements in JavaScript](https://codetogo.io/how-to-get-count-of-dom-elements-in-javascript/)
