### ISSUE TITLE
Use Case Suggestion: remove item from DOM

### ISSUE THREAD

**Issue by MegEdnazednav** [jadjoubran/codetogo.io#104]

**Comment by jadjoubran** [comment]
Thanks! Will add this soon

**Comment by kakadiadarpan** [comment]
**Suggestion**
We can use `.remove()` API of node element:
```javascript
var element = document.getElementById('item-x');
element.remove();
```

**Comment by jadjoubran** [comment]
@kakadiadarpan yep indeed!
I was going to do it tonight, would you like to submit a PR?
If so, please use the same the same code from this [usecase](https://codetogo.io/how-to-add-class-to-element-in-javascript/) in order to keep it consistent

**Comment by kakadiadarpan** [comment]
@jadjoubran Sure I would do it tonight!

**Comment by jadjoubran** [comment]
🎬 [How to remove element from DOM in JavaScript](https://codetogo.io/how-to-remove-element-from-dom-in-javascript/)
