### ISSUE TITLE
Use Case Suggestion: How to register a service worker

### ISSUE THREAD

**Issue by webmaxru** [jadjoubran/codetogo.io#109]
```
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js');
  });
}
```

In this minimalistic sample:
- We do a feature detection
- We use window load event to keep the page load performant
- We encourage to use ES2015 fat arrow syntax

**Comment by kakadiadarpan** [comment]
I think it would be better if we also show how to check the service worker registration status:

```javascript
if('serviceWorker' in window.navigator) {
  window.addEventListener('load', () => {
    window.navigator.serviceWorker.register("/sw.js", { scope: "/" }).then((registration) => {
      console.log("ServiceWorker registration successful with scope: ", registration.scope);
    }).catch((error) => {
      console.error("ServiceWorker registration failed: ", error);
    });
  });
}
```

**Comment by webmaxru** [comment]
That's a good question for the discussion and actually, it's related to how we position codegoto in general:
- a minimalistic code that just works (and you can add what's missing)
- a code with some explanations which you have to remove before using in production (like these console outputs)

Also, here is the link to MDN (to be added to the snippet page):
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register

And I'dd add this extra one:
https://developers.google.com/web/fundamentals/primers/service-workers/registration

**Comment by jadjoubran** [comment]
That's great, thanks @webmaxru!
Indeed, in order to keep it consistent, we'll have to omit the secondary options (such as `scope` and console logs)
There's also a limitation of 1 link only, which is for MDN

**Comment by jadjoubran** [comment]
🎬 [How to register a service worker in JavaScript](https://codetogo.io/how-to-register-a-service-worker-in-javascript/)

**Comment by jadjoubran** [comment]
Based on @kakadiadarpan and @aboustayyef (from a [tweet](https://twitter.com/Beirutspring/status/973170722741870592)), it's worth adding in the sample code how to catch errors that may arise from failed registrations

I think that the `scope` is not very often and can be left out as additional instructions in the `MDN Link`

**Comment by kakadiadarpan** [comment]
Agreed.
