### ISSUE TITLE
Use Case Suggestion: How to play/pause a video in JavaScript

### ISSUE THREAD

**Issue by kissu** [jadjoubran/codetogo.io#11]
```js
const video = document.getElementById('myVideoElement')
video.play()
video.pause()
```

[MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement)

**Comment by jadjoubran** [comment]
Thanks @kissu for this!
This use case requires some HTML code with it and we currently don't have this setup. I'll keep this issue open for the future
Cheers!

**Comment by jadjoubran** [comment]
This is now possible because of #107

**Comment by jadjoubran** [comment]
🎬
- [How to play video in JavaScript](https://codetogo.io/how-to-play-video-in-javascript/)
- [How to pause video in JavaScript](https://codetogo.io/how-to-pause-video-in-javascript/)
- [How to stop video in JavaScript](https://codetogo.io/how-to-stop-video-in-javascript/)
