### ISSUE TITLE
Use Case Suggestion: time/benchmark/profile the execution time of your javascript function

### ISSUE THREAD

**Issue by OdinTech3** [jadjoubran/codetogo.io#113]
Using [perfomance.now](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now), you can get very  accurate results of your javascript function. It's available in modern browsers, below is a snippet of how to use it:

```
let start = performance.now();
func(); // function or snipper of code you want to profile/time/benchmark
let end = performance.now();
console.log(`Call to ${func.name} took ${(end - start)} milliseconds.`);
```

You can wrap it in a decorator and then you'll have something like this:

```
function timeit(func){
    let start = performance.now();
    let val = func();
    let end = performance.now();
    console.log(`Call to ${func.name} took ${(end - start)} milliseconds.`);

    return val;
}
```

**Comment by jadjoubran** [comment]
This is gold, thanks @OdinTech3!
Would you like to submit a PR for it?
If yes, please don't wrap it in a function as all the use cases on CodeToGo aim to show the step by step process rather than giving out "ready to copy" functions

**Comment by OdinTech3** [comment]
Yeah I would be glad to do so!

**Comment by jadjoubran** [comment]
Thanks @OdinTech3!
I'll keep this issue open until we finalize the PR

**Comment by jadjoubran** [comment]
🎬 [How to time a function in JavaScript](https://codetogo.io/how-to-time-a-function-in-javascript/)

I also added a synonym for profile/benchmark/time, so if you search for `benchmarking function`, you'd get this use case as a result!
Cheers!
