### ISSUE TITLE
Use Case Suggestion:  How to get a Single Character from a String

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#114]
var myName = "Qazim";
myName[0];
"Q"
myName[1];
"a"
myName[2];
"z"
myName[3];
"i"
myName[4];
"m"

**Comment by jadjoubran** [comment]
Thanks @politologu! will add soon

**Comment by jadjoubran** [comment]
Closing as similar to [How to get first character of string](https://codetogo.io/how-to-get-first-character-of-string-in-javascript/)
