### ISSUE TITLE
Use Case Suggestion: How to access an Array’s Elements

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#115]
var states = [
 "Kosovo",
 "UK",
 "Sweden",
 "Germany",
 "Dubai",
 "Turkey"
];

states[0];
"Kosovo"
states[3];
"Germany"

**Comment by jadjoubran** [comment]
Thanks @politologu! will add soon

**Comment by politologu** [comment]
@jadjoubran when you approved, can I submit via Pull Request?

**Comment by jadjoubran** [comment]
Yes please, that would be cool!
I'll give you comments (if any) on the PR itself
Cheers!

**Comment by politologu** [comment]
@jadjoubran thanks man!
