### ISSUE TITLE
Use Case Suggestion: How to Join Multiple Arrays  in JavaScript

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#119]
var cars = ["BMW", "Mercedes", "Mini-Coper"]; 
var laptops = ["HP", "Mac"];
var animals = ["Cats", "Dogs"];
var all = cars.concat(laptops, animals);
 all; 

//["BMW", "Mercedes", "Mini-Coper", "HP", "Mac", "Cats", "Dogs"]

**Comment by kakadiadarpan** [comment]
It's already there:
[How to concatenate arrays in JavaScript](https://codetogo.io/how-to-concatenate-arrays-in-javascript/)

**Comment by politologu** [comment]
@kakadiadarpan Yep, now I saw thanks man!
