### ISSUE TITLE
Use Case Suggestion: How to find the Index of an element  in an Array

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#120]
var colors = ["red", "green", "blue"];
 colors.indexOf("blue"); 
//2 
colors.indexOf("green"); 
//1
colors.indexOf("red"); 
//0

**Comment by jadjoubran** [comment]
Thanks @politologu!
Feel free to submit a PR for this one
Cheers

**Comment by jadjoubran** [comment]
related to #127

**Comment by jadjoubran** [comment]
🎬 [How to find index of element in array in JavaScript](https://codetogo.io/how-to-find-index-of-element-in-array-in-javascript/)
