### ISSUE TITLE
Use Case Suggestion: add / remove class on scroll

### ISSUE THREAD

**Issue by levelev** [jadjoubran/codetogo.io#123]
how can i add or remove a class of an element on scroll, for example make transparent navbar white scroll down and transparent again on scroll up

**Comment by jadjoubran** [comment]
Thanks @levelev!
The best way to do this would be using `IntersectionObserver` however browser support for it is still
not that impressive

<img width="1267" alt="screen shot 2018-03-28 at 7 15 15 pm" src="https://user-images.githubusercontent.com/2265232/38042199-5fadf574-32bc-11e8-98bc-8496fc51f1f6.png">

we could keep this issue open for later on until IntersectionObserver becomes more mature
In the meantime, if you'd like to see how you can make it in your project, send me a DM and I can help
Cheers!
