### ISSUE TITLE
Use Case Suggestion: how to call a function in javascript

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#13]

**Comment by jadjoubran** [comment]
Although it sounds very easy, I think this will be useful to developers coming from languages where you don't necessarily need the `()` around the function to call it, such as `ruby`.
Will add this in the next release 👍

**Comment by jadjoubran** [comment]
🎬 [How to call a function in JavaScript](https://codetogo.io/how-to-call-a-function-in-javascript/)

**Comment by politologu** [comment]
yep :)
