### ISSUE TITLE
Use Case Suggestion: How to Passing Multiple Arguments to a function in JavaScript

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#140]
function  printMultipleTimes (howManyTimes, whatILove) { 
 for (var i = 0; i < howManyTimes; i++) {  
  console.log(i + " " + whatILove); 

 } };
printMultipleTimes(5, "I love function"); 

//output
0 I love function
 I love function
2 I love function
 3 I love function
 4 I love function

**Comment by jadjoubran** [comment]
Thanks @politologu 
Unfortunately this goes the same thing as #72 
they're very basic to be included as a "use case"
Thanks for your time!
