### ISSUE TITLE
Use Case Suggestion: How to passing Multiple Arguments to a function in JavaScript

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#144]
var printMultipleTimes = function (howManyTimes, whatToDraw) {
      for (var i = 0; i < howManyTimes; i++) {  
      console.log(i + " " + whatToDraw); 
 } 
};
printMultipleTimes(5, "=^.^=");
 //0 =^.^=
 //1 =^.^= 
//2 =^.^=
 //3 =^.^=
 //4 =^.^=

**Comment by jadjoubran** [comment]
Thanks @politologu 
This is a duplicate of your previous issue here #140

**Comment by politologu** [comment]
@jadjoubran  omg sorry

**Comment by jadjoubran** [comment]
No worries 👍
