### ISSUE TITLE
ordering the use cases

### ISSUE THREAD

**Issue by MiloudiMohamed** [jadjoubran/codetogo.io#146]
Hi, i don't know if you already answered this kind of questions but i find it annoying every time i visit the website to hit **ctrl+f** and  search by date.
so if you can to add a button to order them by their creating date so anyone can knows easily which topics are added.
Thank you

**Comment by jadjoubran** [comment]
Thanks @AdamKeen 
That is indeed a necessary feature
However the problem is that codetogo is a static website right now, so not sure if this will be possible without rebuilding the website as a dynamic web app or using a front-end framework
Will keep this issue open to track it

**Comment by kissu** [comment]
I learned some Nuxt + Netlify recently, this will pretty much suit the app needs. 🌮 
Aka, being super fast, easy to maintain (Nuxt or `.md` with Vuepress), being a PWA 💪 and quickly deployed as soon as any changes are made (hello #137 👼).

Got a project for a buddy right now (and need to finish that `Become an expert: The non-technical training for developers` track 🏮), but I'll clearly give a shot for it if nobody does it before me. 😄

**Comment by jadjoubran** [comment]
Thanks @kissu 😄
