### ISSUE TITLE
Use Case Suggestion: How to use ID to identify elements with DOM in JavaScript

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#147]
`<h1` id="h1-heading">Hello `Codetogo!</h1>`

const headingElement = document.getElementById("h1-heading");

**Comment by jadjoubran** [comment]
Thanks @politologu!
There's already one for it here: [How to find element by id in JavaScript](https://codetogo.io/how-to-find-element-by-id-in-javascript/)
