### ISSUE TITLE
Use Case Suggestion: How to get attribute data from a element

### ISSUE THREAD

**Issue by HRegie** [jadjoubran/codetogo.io#148]
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes.

Thank's

**Comment by jadjoubran** [comment]
Thanks @HRegie!
Will add soon

**Comment by jadjoubran** [comment]
🎬 [How to get data attribute from element in JavaScript](https://codetogo.io/how-to-get-data-attribute-from-element-in-javascript/)
