### ISSUE TITLE
Use Case Suggestion: How to find URL browser with BOM in JavaScript

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#151]
alert(location.href); // shows current URL
if (confirm("Go to codetogo?")) {
  location.href = "https://codetogo.io/"; // redirect the browser to another URL
}

**Comment by jadjoubran** [comment]
Thanks @politologu 
There's a similar use case that allows you to [get the current page URL](https://codetogo.io/how-to-get-current-page-url-in-javascript/)
and for changing it, it's kinda the same variable which you need to change
Thanks!

**Comment by politologu** [comment]
omg sorry :)

**Comment by jadjoubran** [comment]
No worries 😄
