### ISSUE TITLE
better workflow for contributing

### ISSUE THREAD

**Issue by landsman** [jadjoubran/codetogo.io#152]
Hi @jadjoubran,

this is nice project but I don't understand why you don't using better workflow for contributing. Sending issues aren't the best way. Let's create mark-down based templates and let contributors send pull request with changes.

And commit [builded data](https://github.com/jadjoubran/codetogo.io/tree/master/build_production) isn't good too.
Project [@pehapkari/pehapkari.cz](https://pehapkari.cz/blog/2018/04/11/how-anyone-can-write-a-post-here/) is great inspiration for that.

**EDIT:**
Oh, there is markdown, sorry I don't expected that If link on website bring me to issues page.

**Comment by jadjoubran** [comment]
No worries! 😄 I'm glad you like the project though
Looking forward for your contributions!
And I'm planning on removing the `build_production` folder out of the repo since I recently migrated to `netlify`
Cheers!
