### ISSUE TITLE
Use Case Suggestion: How to use spread operator ?

### ISSUE THREAD

**Issue by marcoswca** [jadjoubran/codetogo.io#154]
function myFunction(x, y, z) { 
  console.log(x);
  console.log(y);
  console.log(z);
}
var myArgs = [0, 1, 2];
myFunction(...myArgs);

// 0
// 1
// 2

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

var arr1 = [0, 1, 2];
var arr2 = [3, 4, 5];
arr1.push(...arr2);
console.log(arr1);
//[0, 1, 2, 3, 4, 5];

**Comment by jadjoubran** [comment]
Thanks @marcoswca 
We've got 2 use cases for spread operator:
[How to concatenate objects in JavaScript](https://codetogo.io/how-to-concatenate-objects-in-javascript/)
[How to concatenate arrays in JavaScript](https://codetogo.io/how-to-concatenate-arrays-in-javascript/)

Feel free to re-open or open a new issue if you've got new use cases 😄
