### ISSUE TITLE
"How to deep clone an object in JavaScript" provided solution does not clone nested objects.

### ISSUE THREAD

**Issue by farhantahir** [jadjoubran/codetogo.io#159]
The provided solution for this use case is not valid. As by deep cloning it means that all nested objects will be cloned as well. The `ES6 spread operator` doesn't create clone of nested objects.`` Instead it creates a `Shallow Copy`

https://codetogo.io/how-to-deep-clone-an-object-in-javascript/

```
const person = {
  id: 1,
  name: {
    first: "John",
    last: "Doe"
  }
};

const duplicate = { ...person };
```

**Comment by jadjoubran** [comment]
Thanks @farhantahir for pointing this out! You're absolutely right
I will rename the usecase to: `How to shallow clone an object in JavaScript`
What do you think?

**Comment by jadjoubran** [comment]
Thanks for reporting this!

🎬 [How to create shallow copy of object in JavaScript](https://codetogo.io/how-to-create-shallow-copy-of-object-in-javascript/)
