### ISSUE TITLE
Use Case Suggestion: window scroll

### ISSUE THREAD

**Issue by joxmar** [jadjoubran/codetogo.io#164]
Listen to window scroll event:

`window.addEventListener('scroll', function(){`
`  console.log("They see me scrolling, they hatin'");`
`})`

**Comment by jadjoubran** [comment]
Thanks @joxmar 
Will add this soon

**Comment by jadjoubran** [comment]
🎬 [How to listen to scroll event in JavaScript](https://codetogo.io/how-to-listen-to-scroll-event-in-javascript/)
