### ISSUE TITLE
Use Case Suggestion: timeout

### ISSUE THREAD

**Issue by ChillerDragon** [jadjoubran/codetogo.io#166]
idk how to use ``setTimeout()``

**Comment by jadjoubran** [comment]
🎬
* [How to set timeout in JavaScript](https://codetogo.io/how-to-set-timeout-in-javascript/)
* [How to set interval in JavaScript](https://codetogo.io/how-to-set-interval-in-javascript/)

**Comment by ChillerDragon** [comment]
Awesome thanks!
