### ISSUE TITLE
Use Case Suggestion: cookies

### ISSUE THREAD

**Issue by ChillerDragon** [jadjoubran/codetogo.io#167]

**Comment by ChillerDragon** [comment]
._.

**Comment by jadjoubran** [comment]
Hey @ChillerDragon 
I should have provided an explanation, sorry for that
accessing cookies is blocking, there's a proposal for async cookies but it's not there yet
we could provide a very basic use case for accessing `document.cookie` but I don't feel it will provide a lot of value
