### ISSUE TITLE
Use Case Suggestion:How to compare two objects in JavaScript

### ISSUE THREAD

**Issue by belide** [jadjoubran/codetogo.io#17]

**Comment by jadjoubran** [comment]
Thanks @belide!

**Comment by belide** [comment]
Waiting for this very badly!

**Comment by jadjoubran** [comment]
Hi @belide 
There doesn't seem to be a way to do it without creating a long custom function

If you've got 2 small & identical objects without methods you can compare the string resulting from `JSON.stringify()` of both objects but that doesn't work in all scenarios

Do you have a solution that works all the time and is much shorter than a ~10 line custom method?

**Comment by OdinTech3** [comment]
Wouldn't mind taking a crack at this but can someone help me with an example or explain further what they mean by compare two object in javascript? Like you mean two objects have the same exact properties?

**Comment by jadjoubran** [comment]
Thanks @OdinTech3!
I think it's about comparing 2 objects and checking if they're exactly the same (same properties & values)
I feel like the new `Object.entries` should make this easier but I'm not sure about its browser support

**Comment by OdinTech3** [comment]
So here is my solution to comparing two object: 
### Ex1

```javascript

let a = {
    item1: 1,
    item2: 2,
    item2: 3,
};


let b = {
    item1: 1,
    item2: 2,
    item2: 3,
};

```
A naive comparison is to compare the objects lengths:

```javascript
if (Object.keys(a).length === Object.keys(b).length){
    console.log('True: a and b are equal');
}else{
    console.log('False: a and b are not equal');
}

// output => 'True: a and b are equal'
```
Now if you want to compare the properties and values of object a and b, we could find the [intersection](https://en.wikipedia.org/wiki/Intersection_(set_theory)) between them. So if there is no intersection between a and b, then they are the same but if they are then vice versa. This is how it looks like in code:

```javascript
let intersection = Object.keys(a).filter((aKey) =>{
    if (b.hasOwnProperty(aKey) && b[aKey] === a[aKey]){
        return false;
    }
    return true;
});

console.log(intersection); // => []

if (intersection.length < 1){
    console.log('True: a and b are equal');
}else{
    console.log('False: a and b are not equal');
}
// output => 'True: a and b are equal'
```

### Ex2

```javascript

let a = {
    item1: 1,
    item2: 454,
    item2: 3,
};


let b = {
    item1: 1,
    item2: 2,
    item2: 3,
};
```

```javascript
let intersection = Object.keys(a).filter((aKey) =>{
    if (b.hasOwnProperty(aKey) && b[aKey] === a[aKey]){
        return false;
    }
    return true;
});

console.log(intersection); // => ['item2']

if (intersection.length < 1){
    console.log('True: a and b are equal');
}else{
    console.log('False: a and b are not equal');
}
// output => 'False: a and b are not equal'
```

### Ex3

```javascript

let a = {
    item1: 1,
    item2: function() {
        console.log('HELLO');
    },
};


let b = {
    item1: 1,
    item2: function() {
        console.log('HELLO');
    },
};
```
If you use the same code for checking if two objects are equal with Ex3, it won't output the correct output because the functions in a.item2 and b.item2 are two different object in memory, so in this situation one might have to stringify the values from the objects so to have a more unison comparison:

```javascript
let intersection = Object.keys(a).filter((aKey) =>{
    if (b.hasOwnProperty(aKey) && JSON.stringify(b[aKey]) === JSON.stringify(a[aKey])){
        return false;
    }
    return true;
});

console.log(intersection); // => []

if (intersection.length < 1){
    console.log('True: a and b are equal');
}else{
    console.log('False: a and b are not equal');
}
// output => 'True: a and b are equal'
```

**Comment by jadjoubran** [comment]
Thanks @OdinTech3 for this awesome research 😍
Indeed it makes sense to have different approach for when you've got a function in the properties and when you don't have
How about we then create 2 use cases for that?
One without functions in properties and the other one with potentially functions

**Comment by OdinTech3** [comment]
What do you suggest should be the names of the two use cases?

**Comment by jadjoubran** [comment]
- How to compare two objects in Javascript
- How to compare two objects with functions in Javascript

and from the first use case, we'd add a javascript comment `//does not work if object has functions`

**Comment by OdinTech3** [comment]
Refs pull request [143](https://github.com/jadjoubran/codetogo.io/pull/143)
