### ISSUE TITLE
Use Case Suggestion: How to smooth scroll to any div or element on same page?

### ISSUE THREAD

**Issue by Galzor** [jadjoubran/codetogo.io#171]
Smooth scrolling to any element or div on same page. **Requires jQuery**.
```
  $('a[href^="#"]:not([href=#])').on('click',function (e) {
    e.preventDefault();

    var target = this.hash,
    $target = $(target);

    $('html, body').stop().animate({
        'scrollTop': $target.offset().top
    }, 900, function () {
        window.location.hash = target;
    });
  });
```

**Comment by jadjoubran** [comment]
Thanks @Galzor for this!
We encourage usecases without jQuery as the modern web is very powerful and you can now pretty much do everything without jQuery
We already have a similar usecase to this in vanilla JavaScript:

[How to smooth scroll in JavaScript](https://codetogo.io/how-to-smooth-scroll-in-javascript/)

Cheers!
