### ISSUE TITLE
Use Case Suggestion: Skip values in destructuring

### ISSUE THREAD

**Issue by agoel00** [jadjoubran/codetogo.io#177]
<code>
let [a, b, c] = [ 'useless', 'useless', 'useful']
</code>

```javascript
let [ , , c] = ['useless', 'useless', 'useful']
```

**Comment by jadjoubran** [comment]
Thanks @agoel00 for this!
Will add soon

**Comment by jadjoubran** [comment]
🎬 [How to skip values from array destructuring in JavaScript](https://codetogo.io/how-to-skip-values-from-array-destructuring-in-javascript/)
