### ISSUE TITLE
Use Case Suggestion: Search through an array. 

### ISSUE THREAD

**Issue by theIYD** [jadjoubran/codetogo.io#18]
Traversing an array using Linear Search or Binary Search solves a lot of problems while playing with data. 

Thanks 😉

**Comment by jadjoubran** [comment]
Thanks @theIYD!

**Comment by theIYD** [comment]
Anything for contributions ! ✌️ @jadjoubran

**Comment by jadjoubran** [comment]
do you have by any change some sample code?
I haven't done proper research yet but mots of the answers on codetogo are less than 10 lines at most (of course without using implicit return and short variable names such as `a` and `b`) as the goal is to make the answer understandable for the learner

**Comment by theIYD** [comment]
I have made a open sourced library on functions exclusively. Linear Search and Binary Search implementations are available over there. 

Check it out over here :- https://github.com/theIYD/functions.js/blob/master/src/algorithms/functions/linearSearch.js

**Comment by jadjoubran** [comment]
that's really cool! I just starred it
I love the idea however for now, Code to go is only meant for generic use cases, mainly to avoid overlapping with other websites/repo such as #21 
I'll keep this issue open for Later, as we are adapting based on the audience's feedback 😄

**Comment by theIYD** [comment]
It's absolutely alright ! I will contribute to **Code To Go** on a regular basis. 

Thanks for the star ! ❤️
