### ISSUE TITLE
How to create object from array in JavaScript

### ISSUE THREAD

**Issue by LeusMaximus** [jadjoubran/codetogo.io#183]
I found [this](https://stackoverflow.com/questions/4215737/convert-array-to-object) answer on stackoverflow. So for **How to create object from array in JavaScript** case, you can add additional examples:

```javascript
const apps = ["phone", "calculator", "clock"];
const object = Object.assign({}, apps);
```
or

```javascript
const apps = ["phone", "calculator", "clock"];
const object = {...apps};
```

**Comment by jadjoubran** [comment]
Very good point, thanks!
Would you mind sending a PR with the spread syntax to fix this usecase? And also please update the date: in the YAML header

**Comment by LeusMaximus** [comment]
Maybe it makes sense to leave the old version also? Or there is no possibility to leave two examples for one use case?

**Comment by jadjoubran** [comment]
it's not possible as this is geared towards beginners with a link to MDN whenever possible to get more in depth information

**Comment by jadjoubran** [comment]
Use case updated 👍
[How to create object from array in JavaScript](https://codetogo.io/how-to-create-object-from-array-in-javascript/)
