### ISSUE TITLE
How to find index of element in array in JavaScript

### ISSUE THREAD

**Issue by LeusMaximus** [jadjoubran/codetogo.io#184]
We can also search for an index by some condition using the [`Array.prototype.findIndex()`
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex) method.

**Comment by jadjoubran** [comment]
Thanks @LeusMaximus 
Would you like to send a PR for this?
It's better to discuss the code snippet here first though to maintain consistency
Thanks!

**Comment by jadjoubran** [comment]
Thanks @LeusMaximus, this looks good. Feel free to submit a PR

**Comment by jadjoubran** [comment]
A very similar usecase already exists: http://localhost:3000/how-to-find-index-of-element-in-array-in-javascript/
