### ISSUE TITLE
Use Case Suggestion: How to give parameters a default value in JavaScript

### ISSUE THREAD

**Issue by keenanamigos** [jadjoubran/codetogo.io#19]
```JavaScript
function sum(a, b = 5) {
    return a + b;
}

console.log(sum(2, 3)); // 5
console.log(sum(7)) // 12
```

**Comment by jadjoubran** [comment]
Thanks @keenanamigos!

**Comment by keenanamigos** [comment]
No problem @jadjoubran! This is an awesome project.

**Comment by jadjoubran** [comment]
🎬 [How to define a function with default parameter in JavaScript](https://codetogo.io/how-to-define-a-function-with-default-parameter-in-javascript/)
