### ISSUE TITLE
Use Case Suggestion: Random hex values

### ISSUE THREAD

**Issue by idarwishman** [jadjoubran/codetogo.io#192]
`'#' + Math.floor(Math.random() * 0xFFFFFF).toString(16).padStart(6, '0')`

**Comment by jadjoubran** [comment]
Thanks @idarwishman!
Would you be interested in sending a PR for this? If so, please name the use case as: random hex color
(since it's 6 numbers)

**Comment by jadjoubran** [comment]
🎬 [How to get random hex color in JavaScript](https://codetogo.io/how-to-get-random-hex-color-in-javascript/)
