### ISSUE TITLE
Use Case Suggestion: async wait before continue

### ISSUE THREAD

**Issue by muuvmuuv** [jadjoubran/codetogo.io#194]
Would wait before continueing with executiong in async functions.

```js
const timer = ms => new Promise(r => setTimeout(r, ms)) // <---

async function doSomething() {
   console.log("Start")
   await timer(2000)
   console.log("Stop")
}

doSomething()
```

I used this instead of breakpoints to test my [ora](https://github.com/sindresorhus/ora) spinner.

**Comment by jadjoubran** [comment]
Thanks @muuvmuuv 
would you be up to send it as a PR?
Thanks!

**Comment by jadjoubran** [comment]
🎬 [How to wait in async await functions in JavaScript](https://codetogo.io/how-to-wait-in-async-await-functions-in-javascript/)
