### ISSUE TITLE
Use Case Suggestion: Tons of already made solution for JS

### ISSUE THREAD

**Issue by AzrizHaziq** [jadjoubran/codetogo.io#21]
Hi, i would like to share there is tons of snippets that is publicly shared here. I think you can ask him first 😄 

https://github.com/Chalarangelo/30-seconds-of-code

**Comment by jadjoubran** [comment]
Thanks @AzrizHaziq!
30-seconds-of code is very helpful! Although the 2 ideas may seem a bit similar, there are some differences between the use cases we provide on [codetogo.io](https://codetogo.io) compared to those on 30-seconds-of-code

The use cases covered on 30-seconds-of-code are a bit different than the ones we're covering here.

Is there a particular use case you're interested in?
Cheers!
