### ISSUE TITLE
Use Case Suggestion: How to loop backwards though array in JavaScript

### ISSUE THREAD

**Issue by penance316** [jadjoubran/codetogo.io#22]
const people = ['John', 'Nicole', 'Jad'];

for(var i = people.length; i--;){
     console.log(people[i]);
}

**Comment by jadjoubran** [comment]
Thanks @penance316!

**Comment by jadjoubran** [comment]
I used ES2015's `for .. of` with array.prototype.reverse()

🎬 [How to loop backwards through array in JavaScript](https://codetogo.io/how-to-loop-backwards-through-array-in-javascript/)
