### ISSUE TITLE
Use Case Suggestion: check if element does not have class

### ISSUE THREAD

**Issue by shikkaba** [jadjoubran/codetogo.io#229]

**Comment by jadjoubran** [comment]
Hey! We have a very similar use case to that which is [How to check if element has class in JavaScript](https://codetogo.io/how-to-check-if-element-has-class-in-javascript/)
the result you'll get will simply be `false` instead of `true`
Makes sense?

**Comment by shikkaba** [comment]
That makes sense. I was just hoping there was a way to check if that class was not there other than using an if/else check. Like even being able to put ! infront like in jQuery would be awesome, but you can't do that with that one. I could just not know enough. *shrugs*
