### ISSUE TITLE
Use Case Suggestion: Array to a comma seperated string

### ISSUE THREAD

**Issue by theIYD** [jadjoubran/codetogo.io#23]
```js 
const arr = ['Eat', 'Sleep', 'Code', 'Repeat'];
const result = arr.toString(); // update: .join(',') is more faster. 

console.log(result);
// Eat,Sleep,Code,Repeat
```

Thanks 😉

**Comment by jadjoubran** [comment]
Thanks!
Wouldn't `arry.join(,)` make more sense here?

**Comment by theIYD** [comment]
Considering the speeds, <code>arr.join(',')</code> is faster. 👍 

![screenshot capture - 2017-12-18 - 18-24-10](https://user-images.githubusercontent.com/10477827/34107060-c1efacc2-e420-11e7-9bf3-63d23aecee3f.png)

**Comment by jadjoubran** [comment]
🎬 [How to convert array to comma separated string in JavaScript](https://codetogo.io/how-to-convert-array-to-comma-separated-string-in-javascript/)
