### ISSUE TITLE
Use Case Suggestion:  How to repeat a string

### ISSUE THREAD

**Issue by LeanSeverino1022** [jadjoubran/codetogo.io#233]
let strCode= 'Code';

strCode.repeat(3); // returns "CodeCodeCode"

//repeat method cannot accept a negative number
strCode.repeat(-1); //returns an error

//floats will rounded down to the nearest integer
strCode.repeat(2.7); //CodeCode

**Comment by jadjoubran** [comment]
🎬 [How to repeat a string in JavaScript](https://codetogo.io/how-to-repeat-a-string-in-javascript/)
