### ISSUE TITLE
Use Case Suggestion: how to make a string uppercase

### ISSUE THREAD

**Issue by Kiddylollol** [jadjoubran/codetogo.io#234]
Please help it says
/**
 * @param {string} name
 */
function nameInUpperCase(name){
     name = "";
    return toString(name.toUpperCase);
}

//sample usage
console.log(nameInUpperCase("Jennifer"));
console.log(nameInUpperCase("Diego"));

This is my code in Javascript but it says "Jennifer: is not turning into "Jennifer"
Can you please help me?

**Comment by jadjoubran** [comment]
Please use the support of learnjavascript.online rather than codetogo, thanks!
