### ISSUE TITLE
Use Case Suggestion: Fetch XML

### ISSUE THREAD

**Issue by adamjohnson** [jadjoubran/codetogo.io#235]
Fetch JSON exists, but consider adding fetching XML (for those poor souls that don't have access to JSON). Here's a code snippet:

```js
fetch('http://xml-coreutils.sourceforge.net/food.xml')
  .then(response => response.text())
  .then(data => {
    // console.log(data); // The raw string
    let parser = new DOMParser();
    let xml = parser.parseFromString(data, 'application/xml');
    console.log(xml);
  })
  .catch(console.error);
```

Here's a [YouTube video](https://www.youtube.com/watch?v=MDAWie2Sicc) of Steve Griffith working with JS to fetch XML.

Love Code To Go by the way! Thanks for all you do.

**Comment by jadjoubran** [comment]
Thanks for the use case! And I'm really happy to hear that you love CodeToGo!

I've added https://codetogo.io/api/users.xml as well as the use case: [How to fetch XML in JavaScript](https://codetogo.io/how-to-fetch-xml-in-javascript/)
