### ISSUE TITLE
New idea for codetogo.io 

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#24]
I have an idea!

Please, create a subscribe on codetogo.io   to inform us of every posting, if you can? 

What do you think?

**Comment by jadjoubran** [comment]
Thanks @politologu 
This has already been suggested in #7 
We're going to do it weekly rather than daily as it may become spammy
Cheers!

**Comment by politologu** [comment]
ahaaa sorry I didn't read it
