### ISSUE TITLE
Use Case Suggestion: Sort An Array of objects based on an object property

### ISSUE THREAD

**Issue by Ac-Srikanth** [jadjoubran/codetogo.io#243]

**Comment by jadjoubran** [comment]
Could you provide an object example please?

**Comment by Ac-Srikanth** [comment]
[{name: 'user1', age: 28},
{name: 'user2', age: 21}, 
{name: 'user3', age:'38},
{name:'user4', age:'18}]
Here sort by age can be done

**Comment by jadjoubran** [comment]
Thanks!

**Comment by jadjoubran** [comment]
🎬
- [How to sort array of objects in ascending order in JavaScript](https://codetogo.io/how-to-sort-array-of-objects-in-ascending-order-in-javascript/)
- [How to sort array of objects in descending order in JavaScript](https://codetogo.io/how-to-sort-array-of-objects-in-descending-order-in-javascript/)
