### ISSUE TITLE
Use Case Suggestion: minutesnow

### ISSUE THREAD

**Issue by BBGSch** [jadjoubran/codetogo.io#246]

**Comment by jadjoubran** [comment]
Will add Intl.RelativeTimeFormat once it's implemented on Safari

**Comment by jadjoubran** [comment]
Thank you!

[Get minutes ago in JS](https://codetogo.io/how-to-get-minutes-ago-in-javascript/)
and [Human-friendly date diff](https://codetogo.io/how-to-get-human-friendly-date-difference-in-javascript/)
