### ISSUE TITLE
Use Case Suggestion: sample from array

### ISSUE THREAD

**Issue by dwiehoff** [jadjoubran/codetogo.io#249]
```js
var array = [
  "Apples",
  "Bananas",
  "Pears"
];

var randomItem = array[ Math.floor(Math.random() * array.length) ];
```

**Comment by jadjoubran** [comment]
Hey @dwiehoff 
This already exists here: [How to get random element from array in JavaScript](https://codetogo.io/how-to-get-random-element-from-array-in-javascript/)
