### ISSUE TITLE
Use Case Suggestion: How to check if an object is empty

### ISSUE THREAD

**Issue by sevtapim** [jadjoubran/codetogo.io#254]
function isEmpty(obj) {
   return Object.keys(obj).length === 0;
}
//sample usage
const john = {
    name: "John"
};
isEmpty(john); // should return false
isEmpty({}); // should return true

**Comment by jadjoubran** [comment]
Thank you! [check if object is empty in JavaScript](https://codetogo.io/how-to-check-if-object-is-empty-in-javascript/)
