### ISSUE TITLE
Use Case Suggestion: how to store data to local storage in javascript

### ISSUE THREAD

**Issue by Snapp-Dragon** [jadjoubran/codetogo.io#257]
const money = { 
    
    currency: "United States Dollar",

    value: 20

}

localStorage.setItem("money",JSON.stringify(money));

**Comment by jadjoubran** [comment]
Very good use case, thanks!
I am planning on re-writing the website soon, so I will include this with the re-write

**Comment by BitsNExabytes** [comment]
Thank you. This is the first project I have ever contributed to. Looking to contribute a lot more.
