### ISSUE TITLE
Use Case Suggestion: Parse query string parameters from URL

### ISSUE THREAD

**Issue by johndavidsimmons** [jadjoubran/codetogo.io#27]

**Comment by jadjoubran** [comment]
That's an interesting one! I couldn't find a short solution for it though..
do you have a suggested solution by any chance?
Cheers!

**Comment by jadjoubran** [comment]
it turns out the answer for this one can be achieved by passing
`document.location` to `new URL`
`new URL(document.location)`

There's a newer issue with sample code here #94 
I'll close this one and merge it with #94
