### ISSUE TITLE
Use Case Suggestion: Delete key from an Object

### ISSUE THREAD

**Issue by akash2016** [jadjoubran/codetogo.io#28]
`var car={ type: 'fiat', model: 2006};
  delete car.type
`

**Comment by jadjoubran** [comment]
Thanks @akash2016 
This already exists here: [How to remove a property from object in JavaScript](https://codetogo.io/how-to-remove-a-property-from-object-in-javascript/)

I think you couldn't find it because `remove` and `delete` are not synonyms in Algolia
I'll add them as synonyms now
Cheers!
