### ISSUE TITLE
Use Case Suggestion: Make change to each element of an array

### ISSUE THREAD

**Issue by akash2016** [jadjoubran/codetogo.io#29]
`var old=[1,2,3,4];
  var new=old.map(a => a+1);
`

**Comment by jadjoubran** [comment]
Thanks @akash2016 
Will add in the next release!

**Comment by jadjoubran** [comment]
🎬 [How to apply function to every array element in JavaScript](https://codetogo.io/how-to-apply-function-to-every-array-element-in-javascript/)
