### ISSUE TITLE
Use Case Suggestion: How to convert number into currency  format in javascript

### ISSUE THREAD

**Issue by grafisaholic** [jadjoubran/codetogo.io#290]
function formatCurrency(nominal) {
var str = "";
  var angkarev = nominal.toString().split("").reverse().join("");

  for (var i = 0; i < angkarev.length; i++) {
    if (i % 3 == 0) str += angkarev.substr(i, 3) + ".";
  }
  
  return '$ ' + str.split("", str.length - 1).reverse().join("");
}

const price = formatCurrency(50000)

**Comment by jadjoubran** [comment]
It already exists: [How to format currency as per locale in JavaScript](https://codetogo.io/how-to-format-currency-as-per-locale-in-javascript/)
