### ISSUE TITLE
Use Case Suggestion: How to destructure

### ISSUE THREAD

**Issue by danieldunderfelt** [jadjoubran/codetogo.io#3]
The destructuring syntax may be hard to remember. Here's a handy reference.

```javascript
const obj = {
  key: 'value',
  nested: {
    nestedProperty: 'nested value'
  }
};

const { key, undefinedKey = 'default value', nested: { nestedProperty } } = obj;

console.log(key); // 'value'
console.log(undefinedKey); // 'default value'
console.log(nestedProperty); // 'nested value'
console.log(nested); // undefined
```

**Comment by jadjoubran** [comment]
Awesome, thanks @danieldunderfelt 
Will add it in the next release!

**Comment by danieldunderfelt** [comment]
This is a great project, @jadjoubran! The only criticism I have is that there's not that much content yet, so I thought I'd contribute :D

**Comment by jadjoubran** [comment]
Thanks @danieldunderfelt 😄 We launched Minimum Viable Product style with only 26 use cases 😅 we didn't expect this awesome feedback from the community!
We're going to go up to 100 use cases by the end of the year or even earlier 🎉

**Comment by danieldunderfelt** [comment]
Awesome, great to hear! Good luck! 😃👍

**Comment by jadjoubran** [comment]
🎬 2 use cases live:

👉  [How to destructure from array in JavaScript](https://codetogo.io/how-to-destructure-from-array-in-javascript/)
👉 [How to destructure from object in JavaScript](https://codetogo.io/how-to-destructure-from-object-in-javascript/)

I'll keep this issue open as I feel we could break down your reference into multiple use cases

**Comment by danieldunderfelt** [comment]
Nice! Yeah the default value is especially useful.

**Comment by politologu** [comment]
@jadjoubran also I with pleasure I am ready to contribute :)

**Comment by jadjoubran** [comment]
🎬 [How to destructure with default value in JavaScript](https://codetogo.io/how-to-destructure-with-default-value-in-javascript/)
