### ISSUE TITLE
Use Case Suggestion: Convert array like elements to array

### ISSUE THREAD

**Issue by akash2016** [jadjoubran/codetogo.io#30]
`function check(){
var arg= Array.prototype.slice.call(arguments);
typeof(arg) //object
}`

**Comment by jadjoubran** [comment]
Thanks @akash2016 
Can you give an example for how and when you'd use this?

**Comment by akash2016** [comment]
Array like elements have only .length method available to them. Arguments of a function can be accessed inside the function as array like elements. So if you need to perform any operation on each of the arguments you can convert them in array and use map or similar methods. Bind polyfill internally uses the same mechanism.

**Comment by jadjoubran** [comment]
Ah okay!
So the modern answer to that would be to use the spread operator in ES2015:

```
function test(...args){
    console.log(args);
}

test(1, 2, 3);//[1, 2, 3]
```

is this what you mean?

**Comment by akash2016** [comment]
Exactly!

**Comment by jadjoubran** [comment]
🎬 [How to get function arguments as array in JavaScript](https://codetogo.io/how-to-get-function-arguments-as-array-in-javascript/)
