### ISSUE TITLE
Open source it

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/codetogo.io#31]
Great suggestion from @itamark

Reference from #25 
```
@jadjoubran in general - you should open-source this.  
Suggesting new entries is not what I had in mind when I clicked "Contribute".  
You can still be editor and merge things or not, but it'd be great if people could contribute actual new examples.
```

To keep track of it, here are the steps that I need to take in order to open source it and allow people to contribute with the files directly:

- [x] Refactor some mess 😄 
- [x] Automate versionning
- [x] Add editorconfig
- [x] Remove algolia keys from sync script and set them as environment variables
- [x] Open source it
- [x] Complete [Github's community checklist](https://github.com/jadjoubran/codetogo.io/community)
- [x] Write contribution instructions & guidelines (how to name files, one use case per PR, etc..)
- [x] Provide a sample use case file that can be used for new (PR) contributions
- [x] How to auto-deploy on new PRs? Need Continuous Deployment => Will automate once there is considerable volume

One thing I'm not sure about as well is whether this project will remain a statically generated website or if it'll evolve into a dynamic website

**Comment by theIYD** [comment]
Open source ❤️

**Comment by itamark** [comment]
Yalla! :-)

**Comment by lauragift21** [comment]
Nice. :+1: :heart:

**Comment by jadjoubran** [comment]
And this is done 🎉 
Feel free to open a new issue if you've got additional questions or suggestions

**Comment by politologu** [comment]
Well done!
