### ISSUE TITLE
Use Case Suggestion: On topic "How to increment a variable in JavaScript"

### ISSUE THREAD

**Issue by loddaa** [jadjoubran/codetogo.io#317]
The answer is not correct and not complete. (from : [https://codetogo.io/how-to-increment-a-variable-in-javascript/](url)

The original answer is (postfix):
input : 
`let counter = 0;
counter++;`

output : 
`1` **<-- Not correct** 
`// Should return 0`

-------------------------------------------
**To add to the answer :**

Increment/decrement using (prefix) : 
input:
`let counter = 0;`
`++counter;`

output : 
`1`

See doc : [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment](url)

**Comment by jadjoubran** [comment]
Thank you, updated! It will take a while for the cache to purge though
