### ISSUE TITLE
Use Case Suggestion:Sort element of an array in descending order

### ISSUE THREAD

**Issue by akash2016** [jadjoubran/codetogo.io#32]
`var a=[1,2,3,4,5];
a.sort((b,c) =>  c-b);
`

**Comment by jadjoubran** [comment]
🎬

- [How to sort array in ascending order in JavaScript](https://codetogo.io/how-to-sort-array-in-ascending-order-in-javascript/)
- [How to sort array in descending order in JavaScript](https://codetogo.io/how-to-sort-array-in-descending-order-in-javascript/)
