### ISSUE TITLE
Use Case Suggestion: Reverse elements of an array

### ISSUE THREAD

**Issue by akash2016** [jadjoubran/codetogo.io#33]
`var a=[1,2,3,4,5];
a.reverse();
`

**Comment by jadjoubran** [comment]
there's a similar use case here: [how to loop backwards through array in JavaScript](https://codetogo.io/how-to-loop-backwards-through-array-in-javascript/)
but it makes sense to create a dedicated use case for it as well 👍

**Comment by jadjoubran** [comment]
🎬 [How to reverse elements of array in JavaScript](https://codetogo.io/how-to-reverse-elements-of-array-in-javascript/)
