### ISSUE TITLE
Use Case Suggestion:Add item to localStorage

### ISSUE THREAD

**Issue by akash2016** [jadjoubran/codetogo.io#37]
`localStorage.setItem("a","1");
// Here a is key and 1 is value. Value should be string for local Storage
`

**Comment by jadjoubran** [comment]
🎬

* [How to add item to localstorage in JavaScript](https://codetogo.io/how-to-add-item-to-localstorage-in-javascript/)
* [How to add object to localstorage in JavaScript](https://codetogo.io/how-to-add-object-to-localstorage-in-javascript/)
* [How to remove item from localstorage in JavaScript](https://codetogo.io/how-to-remove-item-from-localstorage-in-javascript/)
