### ISSUE TITLE
Use Case Suggestion: Humanize a number

### ISSUE THREAD

**Issue by theIYD** [jadjoubran/codetogo.io#39]
```js
const humanizeNumber = num => {
     let array = ["th","st","nd","rd"]
     let firstDigit = num % 10;
     return  firstDigit< 4 ? num + array[firstDigit] : num + array[0];
 }

console.log(humanizeNumber(125));
//=> 125th
```

You could also add test for number to be not undefined.
Reference: https://goo.gl/BgTfwU

Thanks 😉

**Comment by kls-89** [comment]
Very cool concept. Looks like it doesn't properly handle the range 11 - 13 (11-13, 111-113, 211-213, etc).

**Comment by theIYD** [comment]
Thanks for the issue @kls-89. I will try to fix the logic.
