### ISSUE TITLE
https://nicolesaidy.com/ redirects to dodgy site.

### ISSUE THREAD

**Issue by gveneyjr** [jadjoubran/codetogo.io#394]
In the site's footer, there's a "Designed by Nicole Saidy". For some reason, the link redirects away from https://nicolesaidy.com/ to a strange site.

**Comment by jadjoubran** [comment]
Thank you for letting me know! Update is on the way and will be live in the next few minutes 👍🏼

**Comment by gveneyjr** [comment]
Certainly! By the way, your learnhtmlcss course, which I just purchased, has been incredibly helpful. You're a great teacher. Cheers.

**Comment by jadjoubran** [comment]
Thank you so much! That's great to hear!
