### ISSUE TITLE
Use Case Suggestion: How to determine if an object is an object

### ISSUE THREAD

**Issue by MitchLillie** [jadjoubran/codetogo.io#4]
```javascript
Object.prototype.toString.call(obj) === '[object Object]'
```

Source: https://toddmotto.com/understanding-javascript-types-and-reliable-type-checking/#true-object-types

Cool site :)

**Comment by jadjoubran** [comment]
Thanks @MitchLillie! 
I'm a big fan of Todd Motto's blog, however we're keeping all the links pointing to MDN right now, especially with the recent news that Microsoft and Google will be putting all of their documentations on MDN

What would be a good MDN link for this one?

**Comment by MitchLillie** [comment]
@jadjoubran I think this would work: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString

**Comment by jadjoubran** [comment]
🎬 [How to check if variable is an object in JavaScript](https://codetogo.io/how-to-check-if-variable-is-an-object-in-javascript/)
