### ISSUE TITLE
Use Case Suggestion:

### ISSUE THREAD

**Issue by milleson** [jadjoubran/codetogo.io#43]
The source of our values is an object like this:
 
```javascript
var info = {
		"full_name" : "John Smith",
		"title" : "Staff Author",
		"links" : [
				{ "blog"     : "http://iviewsource.com" },
				{ "facebook" : "http://facebook.com/iviewsource" },
				{ "podcast"  : "http://feeds.feedburner.com/authoredcontent" },
				{ "twitter"  : "http://twitter.com/planetoftheweb" },
				{ "youtube"  : "http://www.youtube.com/planetoftheweb" }
			]
		};
//The html element on the page is this:
<h2>Links</h2>
<ol id="links">
</ol>
```

The JavaScript code to do the collecting of values uses a standard For-Loop (to loop through the links array sequentially) and a For-In Loop (that outputs each key in the numerical order of the elements in the array) which together look like this (and we check for the presence of the key (using: hasOwnProperty) to get its value and nothing extraneous):

```javascript
var output = '';

for (var i = 0; i <= info.links.length; i++) {
	for (key in info.links[i]) {
		if (info.links[i].hasOwnProperty(key)) {
			output += '<li>' +
			'<a href = "' + info.links[i][key] +
			'">' + key + '</a>' +
			'</li>';
		} // hasOwnProperty check
	} // for each object
} //for each array element
```

**Comment by jadjoubran** [comment]
Thanks @milleson!
There are too many use cases in this one, can you simplify it into 1 small use case just like the other ones we have on [codetogo.io](https://codetogo.io)?
Keep in mind that we already have one for [looping over arrays](https://codetogo.io/how-to-loop-through-array-in-javascript/)
and we also have another one for [template strings](https://codetogo.io/how-to-interpolate-in-javascript/)

**Comment by jadjoubran** [comment]
Feel free to re-open
