### ISSUE TITLE
Use Case Suggestion: Create new array from existing array

### ISSUE THREAD

**Issue by akash2016** [jadjoubran/codetogo.io#44]
`var a=[1,2,3,4]
var b=a.slice(0); // Here b is deep copy of a
`

**Comment by jadjoubran** [comment]
Thanks @akash2016!
This can be achieved in a more modern way using the spread operator `...`
`const b = [...a]`

**Comment by jadjoubran** [comment]
🎬 [How to create array from existing array in JavaScript](https://codetogo.io/how-to-create-array-from-existing-array-in-javascript/)
