### ISSUE TITLE
Use Case Suggestion: Get item from sessionStorage

### ISSUE THREAD

**Issue by akash2016** [jadjoubran/codetogo.io#46]
`sessionStorage.getItem("a");`

**Comment by jadjoubran** [comment]
Thanks @akash2016 
This already exists here: [How to get item from localstorage in JavaScript](https://codetogo.io/how-to-get-item-from-localstorage-in-javascript/)

**Comment by jadjoubran** [comment]
Sorry just saw that you were talking about `sessionStorage` rather than `localStorage` 😅

**Comment by jadjoubran** [comment]
🎬 [How to get item from sessionstorage in JavaScript](https://codetogo.io/how-to-get-item-from-sessionstorage-in-javascript/)
