### ISSUE TITLE
Use Case Suggestion: How to implement Ajax in Javascript

### ISSUE THREAD

**Issue by suleimanbashiru** [jadjoubran/codetogo.io#47]
How to implement Ajax in Javascript.

**Comment by jadjoubran** [comment]
Thanks @suleimanbashiru 
This already exists here: [How to fetch json in JavaScript](https://codetogo.io/how-to-fetch-json-in-javascript/)
Are you looking for something else in particular?

**Comment by jadjoubran** [comment]
Feel free to re-open
