### ISSUE TITLE
Use Case Suggestion: degree to radians

### ISSUE THREAD

**Issue by theIYD** [jadjoubran/codetogo.io#48]
**_function degToRad_**: Convert degrees to radians

```js
const degToRad = deg => {
    return deg * (Math.PI / 180);
}

console.log(degToRad(90));
//=> 1.5707963267948966
```

Thanks @jadjoubran 😃

**Comment by jadjoubran** [comment]
Awesome, thanks @theIYD

**Comment by jadjoubran** [comment]
🎬 [How to convert from degree to radian in JavaScript](https://codetogo.io/how-to-convert-from-degree-to-radian-in-javascript/)
