### ISSUE TITLE
Use Case Suggestion: how to spread a string into multiple array elements

### ISSUE THREAD

**Issue by kissu** [jadjoubran/codetogo.io#5]
If you're building a Konami code for example and want to check if the user's input is correct and don't want to write by hand something like

```js
const stringToMatch = ['y', 'o', 'l', 'o']
```
just type
```js
const stringToMatch = [...'yolo']
```

**Comment by jadjoubran** [comment]
awesome, thanks @kissu!
Will add it in the next release

**Comment by jadjoubran** [comment]
🎬 2 use cases live:

👉  [How to destructure from array in JavaScript](https://codetogo.io/how-to-destructure-from-array-in-javascript/)
👉 [How to destructure from object in JavaScript](https://codetogo.io/how-to-destructure-from-object-in-javascript/)

**Comment by jadjoubran** [comment]
🎬 [How to split string into array of characters in JavaScript](https://codetogo.io/how-to-split-string-into-array-of-characters-in-javascript/)
