### ISSUE TITLE
Use Case Suggestion: isEven

### ISSUE THREAD

**Issue by theIYD** [jadjoubran/codetogo.io#51]
Check if a number is even. Returns true if even, else returns false.

```js
const isEven = (number) => {
    return number % 2 === 0;
}

console.log(isEven(12));
//=> true
```

Thanks @jadjoubran 😃

**Comment by jadjoubran** [comment]
Awesome, thanks!

**Comment by jadjoubran** [comment]
🎬

- [How to check if number is even in JavaScript](https://codetogo.io/how-to-check-if-number-is-even-in-javascript/)
- [How to check if number is odd in JavaScript](https://codetogo.io/how-to-check-if-number-is-odd-in-javascript/)
