### ISSUE TITLE
Use Case Suggestion: Create a DOMNodeList

### ISSUE THREAD

**Issue by theIYD** [jadjoubran/codetogo.io#52]
How to create a **DOMNodeList** ?

```js
const nodelist = document.querySelectorAll(element);
```

Thanks @jadjoubran

**Comment by jadjoubran** [comment]
Thanks @theIYD

Is this different than this usecase? [How to find multiple DOM elements in JavaScript](https://codetogo.io/how-to-find-multiple-DOM-elements-in-javascript/)

Beginners won't be very familiar with the term DOMNodeList

**Comment by theIYD** [comment]
Lol, it is the same thing.
