### ISSUE TITLE
Use Case Suggestion: nth Root of a positive number

### ISSUE THREAD

**Issue by theIYD** [jadjoubran/codetogo.io#53]
Calculate **nth** Root of a positive number

```js
/**
 * @function nthRoot: Calculates the nth root of a positive number
 * @param {Integer} number 
 * @param {Integer} n 
 */
const nthRoot = (number, n) => {
    return Math.pow(number, 1 / n);
}

console.log(nthRoot(16,2));
//=> 4
```

Reference: https://github.com/theIYD/functions.js/commit/e48fdd6f0a196c51aec6f3c1abe995410c7f3494
Thanks @jadjoubran

**Comment by jadjoubran** [comment]
🎬 [How to find root of positive number in JavaScript](https://codetogo.io/how-to-find-root-of-positive-number-in-javascript/)
