### ISSUE TITLE
Use Case Suggestion: How to create a switch statement in javascript

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#55]
// Set the current day of the week to a variable, with 1 being Monday and 7 being Sunday

const day = new Date().getDay();

switch (day) {
    case 1:
        console.log("Happy Monday!");
        break;
    case 2:
        console.log("It's Tuesday. You got this!");
        break;
    case 3:
        console.log("Hump day already!");
        break;
    case 4:
        console.log("Just one more day 'til the weekend!");
        break;
    case 5:
        console.log("Happy Friday!");
        break;
    case 6:
        console.log("Have a wonderful Saturday!");
        break;
    case 7:
        console.log("It's Sunday, time to relax!");
        break;
    default:
        console.log("Something went horribly wrong...");
}
Output
'Just one more day 'til the weekend!'

**Comment by jadjoubran** [comment]
[MDN Link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch)

**Comment by jadjoubran** [comment]
🎬 [How to create a switch statement in JavaScript](https://codetogo.io/how-to-create-a-switch-statement-in-javascript/)
