### ISSUE TITLE
Use Case Suggestion: How to create Comments in Javascript

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#56]
Let's take a quick look at the two different types of JavaScript comment syntax.

Single-line comments are written with two forward slashes // 
// This is a comment
let x = 32;    // assign numerical value to x

Block comments, sometimes referred to as multi-line comments, are written with opening tags /* and closing tags */.

/* This is
a comment */

/**
 * Initialize constant with an array of strings.
 * Loop through each item in the array and print
 * it to the console.
 */

const days = ["Monday", "Tuesday", "Wednesday"];

for (const days of days) {
  console.log(seaCreature);
}

**Comment by jadjoubran** [comment]
🎬 [How to comment in JavaScript](https://codetogo.io/how-to-comment-in-javascript/)
