### ISSUE TITLE
Use Case Suggestion:

### ISSUE THREAD

**Issue by harish-geeky** [jadjoubran/codetogo.io#57]
How to deep clone an object in Javascript
Libraries like lodash etc. do only one level cloning of object in javascript. Using this you can clone the object of/at any level.

input.cloned_object = JSON.parse(JSON.stringify(input.subject_object));

**Comment by jadjoubran** [comment]
Thanks @harish-geeky 
I'll add this use case but using a newer answer, ES2015's spread operator

**Comment by jadjoubran** [comment]
🎬 [How to deep clone an object in JavaScript](https://codetogo.io/how-to-deep-clone-an-object-in-javascript/)

**Comment by harish-geeky** [comment]
Nice! Thanks

**Comment by harish-geeky** [comment]
What tool/editor are you using to show the pretty .js code on your website?

**Comment by jadjoubran** [comment]
[prism js](http://prismjs.com/)
