### ISSUE TITLE
How to output variables in a string in ES6

### ISSUE THREAD

**Issue by khalilsarabey** [jadjoubran/codetogo.io#6]
```javascript
var myName = 'My name is ${fullname}.';
var url = 'http://mysite.com/api/user/${id}';
console.log(myName); //My name is Khalil
console.log(url); // http://mysite.com/api/user/123
```

**Comment by jadjoubran** [comment]
Thanks @khalilsarabey!
We already have that use case here:
[How to interpolate in javascript](https://codetogo.io/how-to-interpolate-in-javascript/)

**Comment by jadjoubran** [comment]
Feel free to re-open if you've got further suggestions on this particular use case!
Cheers

**Comment by khalilsarabey** [comment]
That's cool @jadjoubran ! I didn't check the entire list on the site :) 
I think you can take it a step further by providing an expression interpolation example like: 

`var calculate = '1+1 = ${ 1 + 1 }';`
`console.log(calculate); //1+1 = 2`

**Comment by jadjoubran** [comment]
Awesome idea, will push this today! 😄 

<img width="750" alt="interpolate" src="https://user-images.githubusercontent.com/2265232/34070617-a732695c-e271-11e7-8b7a-0632431f9553.png">

**Comment by jadjoubran** [comment]
Updated use case is live
https://codetogo.io/how-to-interpolate-in-javascript/
