### ISSUE TITLE
Use Case Suggestion: toTitleCase

### ISSUE THREAD

**Issue by theIYD** [jadjoubran/codetogo.io#61]
Get a title cased string.

```js

const toTitleCase = (str) => {
    return str.toString().replace(/\w\S*/g, (text) => text.charAt(0).toUpperCase() + 
           text.substr(1).toLowerCase());
}

console.log('code to go is awesome.');
//=> 'Code To Go Is Awesome.'
```

**Comment by jadjoubran** [comment]
Thanks @theIYD 
This is the same as this one right?
[How to uppercase every word in JavaScript](https://codetogo.io/how-to-uppercase-every-word-in-javascript/)

**Comment by theIYD** [comment]
Ooops yes, 

Sorry for the mistake. 

Thanks @jadjoubran

**Comment by jadjoubran** [comment]
cool no worries!
