### ISSUE TITLE
Use Case Suggestion: How to create  && (AND) logical operator in JavaScript! 

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#64]
// create && (AND) logical operators in JavaScript! 

var hadShower = true;
var hasBackpack = false;
hadShower && hasBackpack;

// out false

**Comment by politologu** [comment]
@jadjoubran sorry for any mistake, sure you can edit maybe title :) or...

**Comment by jadjoubran** [comment]
🎬 [How to create logical AND condition in JavaScript](https://codetogo.io/how-to-create-logical-AND-condition-in-javascript/)
