### ISSUE TITLE
Use Case Suggestion: How to create || (OR) Logical Operator in Javascript

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#65]
//Create  || (OR) Logical Operator in Javascript!

var hasApple = true;
var hasOrange = false;
hasApple || hasOrange;

// out true

**Comment by jadjoubran** [comment]
🎬 [How to create logical NOT condition in JavaScript](https://codetogo.io/how-to-create-logical-NOT-condition-in-javascript/)
