### ISSUE TITLE
Use Case Suggestion: How to create !(NOT) Logical Operator in Javcascript 

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#66]
//Create  !(NOT) Logical Operator in Javascript!

var isWeekend = true;
var needToShowerToday = !isWeekend;
needToShowerToday;

// out false

**Comment by jadjoubran** [comment]
🎬 [How to create logical NOT condition in JavaScript](https://codetogo.io/how-to-create-logical-NOT-condition-in-javascript/)
