### ISSUE TITLE
New Idea (Project) -Learn CSS3!

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#67]
@jadjoubran 

I hope you are well!

Hey Jad, I have an idea, what do you think to create a project similarly such as codetogo.io I mean how2codescss3.io 

Sure, together and other contributors!

Thanks
Qazim Rama

**Comment by theIYD** [comment]
@politologu A good idea maybe. I still don't know the syntax of animations xD 🤣

**Comment by jadjoubran** [comment]
Thanks @politologu 
We were actually planning on adding other languages/softwares, for example `git` in the future also under codetogo.io so it won't remain only for JavaScript

I'm not sure though what kind of use cases we can cover for CSS since most of the properties are kinda self-explanatory (width is width, padding is padding, etc..)

Do you have some examples?

**Comment by theIYD** [comment]
@jadjoubran The use cases might be related to heavy like animations, grid, flexbox, prefixes like webkit and so on ..

**Comment by politologu** [comment]
@theIYD @jadjoubran  we will start from scratch, and as for CSS animations if can I say is about advanced, means is not required!

**Comment by politologu** [comment]
yep is not easy such as with Javascript

**Comment by politologu** [comment]
an example:

<style type="text/css">
h1 {
        color: pink;
}
</style>

<h1>Hello, CSS3!</h1>

**Comment by politologu** [comment]
``<style type="text/css">
h1 {
        color: pink;
}
</style>

<h1>Hello, CSS3!</h1>

**Comment by politologu** [comment]
<style type="text/css">
h1 {
        color: DeepSkyBlue;
}
</style>

<h1>Hello, 

- world!</h1>``

**Comment by politologu** [comment]
![capture](https://user-images.githubusercontent.com/8106609/34456946-92409efa-eda3-11e7-893f-520eac689e82.PNG)

**Comment by politologu** [comment]
<style type="text/css">
h1 {
        color: pink;
}
</style>

<h1>Hello, `CSS3!</h1>`

**Comment by politologu** [comment]
but the h1 tag is not showing
