### ISSUE TITLE
Use Case Suggestion: Create Dynamic Object from Array

### ISSUE THREAD

**Issue by cychainey** [jadjoubran/codetogo.io#68]
I've found myself in need of this one on the odd occasion.

```javascript
const array = [12,27,'str','anotherStr']
const obj = {}
array.map((val, idx)=>obj['key' + [idx]] = val)
console.log(obj)
/*** obj = {key0: 12, key1: 27, key2: "str", key3: "anotherStr"} ***/
```
Hope it helps someone @jadjoubran

**Comment by jadjoubran** [comment]
Thankks @cychainey!

**Comment by jadjoubran** [comment]
🎬 [How to create object from array in JavaScript](https://codetogo.io/how-to-create-object-from-array-in-javascript/)
