### ISSUE TITLE
Business suggestion: a subscription to a newsletter to get an email...

### ISSUE THREAD

**Issue by nfilzi** [jadjoubran/codetogo.io#7]
...automatically any time a new snippet has been added 😬

**Comment by jadjoubran** [comment]
Awesome idea @nfilzi, thanks 😄 
Maybe weekly would make more sense in order to avoid spamming people

**Comment by jadjoubran** [comment]
Done 🎉 
Subscribe on the [landing page](https://codetogo.io/)
