### ISSUE TITLE
Use Case Suggestion:How to Combining logical Operators

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#71]
var isWeekend = false;
var timeCode = true;
var hasApple = false;
var hasCoffee = true;
var shouldLearnToJavascript = !isWeekend && timeCode && (hasApple || hasCoffee);
shouldLearnToJavascript; 

// out 
true

**Comment by jadjoubran** [comment]
Thanks @politologu 
These 3 use cases (#71, #72, #73) are extremely easy so we won't be adding them to codetogo at the moment

Thanks for your time!

**Comment by politologu** [comment]
No problem bro :)!
