### ISSUE TITLE
How to listen to hover event in JavaScript

### ISSUE THREAD

**Issue by BrahimS** [jadjoubran/codetogo.io#75]
```javascript
const element = document.querySelector('css-selector'); 

element.addEventListener('mouseover', (event) => {
  console.log(event.target);
 });

```

**Comment by jadjoubran** [comment]
Thanks @BrahimS!
Will add these new use cases soon

**Comment by BrahimS** [comment]
Your welcome @jadjoubran.
Thanks for this good project 💯

**Comment by jadjoubran** [comment]
🎬 [How to listen to hover event in JavaScript](https://codetogo.io/how-to-listen-to-hover-event-in-javascript/)
