### ISSUE TITLE
Use Case Suggestion: How to test if an object include a value

### ISSUE THREAD

**Issue by nucliweb** [jadjoubran/codetogo.io#81]
How ti test if an object include a value
```
const person = {
  first_name: 'Joan',
  last_name: 'León',
  twitter: '@nucliweb'
};

Object.values(person).includes('@nucliweb');
```

Output
```
true
```

**Comment by jadjoubran** [comment]
Thanks for this @nucliweb 😄
Will add soon!

**Comment by jadjoubran** [comment]
This was recently added, but will only be visible once I finish #83

**Comment by jadjoubran** [comment]
🎬 [How to check if object includes value in JavaScript](https://codetogo.io/how-to-check-if-object-includes-value-in-javascript/)

**Comment by nucliweb** [comment]
Thanks!
