### ISSUE TITLE
Use Case Suggestion: How to test if an object include a substring

### ISSUE THREAD

**Issue by nucliweb** [jadjoubran/codetogo.io#82]
How ti test if an object include a substring
```
const person = {
  first_name: 'Joan',
  last_name: 'León',
  twitter: '@nucliweb'
};

Object.values(person).toString().includes('nucliweb');
```

Output
```
true
```

**Comment by jadjoubran** [comment]
Thanks for this Joan!
Will add soon

**Comment by jadjoubran** [comment]
This was recently added, but will only be visible once I finish #83

**Comment by nucliweb** [comment]
👌

**Comment by jadjoubran** [comment]
🎬 [How to check if object includes substring in JavaScript](https://codetogo.io/how-to-check-if-object-includes-substring-in-javascript/)

**Comment by nucliweb** [comment]
Thanks!
