### ISSUE TITLE
How to extend object

### ISSUE THREAD

**Issue by KhaledNobani** [jadjoubran/codetogo.io#84]
```javascript
let base = { name: "John Doe", age: "31" },
     other = { position: "Manager", title: "Product Manager" };

for (prop in other) {
    base[prop]= other[prop];
}
```

**Comment by jadjoubran** [comment]
Thanks @KhaledNobani for suggesting a new use case! 😄
This looks like a great use case!
With ES2016, it can be done using the spread operator as following:

```
let base = { name: "John Doe", age: "31" },
     other = { position: "Manager", title: "Product Manager" };
let merged = {...base, ...other}
```

I will add this use case soon!

**Comment by jadjoubran** [comment]
🎬 [How to concatenate objects in JavaScript](https://codetogo.io/how-to-concatenate-objects-in-javascript/)
