### ISSUE TITLE
Use Case Suggestion: How to traverse tree in javascript

### ISSUE THREAD

**Issue by tomastrajan** [jadjoubran/codetogo.io#87]
Traversing tree data structure, eg objects with children property recursively to arbitrary depth is useful for interviews and also in practice when implementing with stuff like file explorer or multi level nested menus.

**Comment by jadjoubran** [comment]
Thanks @tomastrajan for this!
Do you happen to have a code example for this? even pseudo code

**Comment by tomastrajan** [comment]
Not really but it's about recursively traversing children until the desired element is found.

**Comment by jadjoubran** [comment]
okay cool 👍 
I will research that soon

**Comment by OdinTech3** [comment]
I don't mind giving this a try. @jadjoubran how many lines of code do you recommend this to be?

**Comment by jadjoubran** [comment]
Thanks @OdinTech3!
Most use cases on CodeToGo are at most 2 to 3 lines of readable javascript code
If it turns out to be a complicated method then it's probably better suited for [30-seconds-of-code](https://github.com/Chalarangelo/30-seconds-of-code) than codetogo
