### ISSUE TITLE
Use Case Suggestion: Formatting currency as per the locale of the user with currency symbol.

### ISSUE THREAD

**Issue by kakadiadarpan** [jadjoubran/codetogo.io#89]
In case of India, for Indian National Rupee(INR):
```javascript
100.42 .toLocaleString("en-IN", { style: "currency", currency: "INR" });
```
which outputs:
`"₹ 100.42"`

<img width="508" alt="screen shot 2018-02-23 at 11 19 33" src="https://user-images.githubusercontent.com/10805593/36629988-bfde1664-1984-11e8-822e-df4810279974.png">

It also takes care of the formatting as per the locale.

**Comment by jadjoubran** [comment]
This is awesome! Thanks @kakadiadarpan 
Would you like to submit a PR?
I would just wrap 100.42 with parenthesis to make it clearer:

`(100.42).toLocale...`

**Comment by kakadiadarpan** [comment]
Sure! I'll do that.

**Comment by jadjoubran** [comment]
🎬 [How to format curreny as per locale in JavaScript](https://codetogo.io/how-to-format-curreny-as-per-locale-in-javascript/)
Thanks @kakadiadarpan! 😄
