### ISSUE TITLE
Topic suggestion: Date related use cases

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/codetogo.io#9]
Will be adding date related use cases, such as:

- How to get timestamp
- How to get date of today
- How to get current day
- How to get current month
- How to format a date

some of the answers will contain references to the Intl API that solves the need to manually define the months names

Feel free to suggest other use cases that will be helpful! 🚀

**Comment by politologu** [comment]
@jadjoubran I think that this site will serve even those who want to learn from the beginning(from scratch), and my suggestion is to post also use cases BEGINNER JAVASCRIPT :) and sure use cases more depth.

Great for this initiative and I love this!

Thanks
Qazim Rama

**Comment by theIYD** [comment]
Had **Code To Go** been there a while ago, learning curve would have been much shorter. 

Thanks for this project ! @jadjoubran

**Comment by jadjoubran** [comment]
I'm glad you like it 😄

**Comment by jadjoubran** [comment]
🎬
- [How to get current timestamp in JavaScript](https://codetogo.io/how-to-get-current-timestamp-in-javascript/)
-[How to get current timestamp in seconds in JavaScript](https://codetogo.io/how-to-get-current-timestamp-in-seconds-in-javascript/)
- [How to convert date to timestamp in JavaScript](https://codetogo.io/how-to-convert-date-to-timestamp-in-javascript/)

**Comment by politologu** [comment]
@jadjoubran many thanks

**Comment by jadjoubran** [comment]
🎬
- [How to get current day name in JavaScript](https://codetogo.io/how-to-get-current-day-name-in-javascript/)
- [How to get current month name in JavaScript](https://codetogo.io/how-to-get-current-month-name-in-javascript/)
- [How to convert date to mysql format YYYY MM DD in JavaScript](https://codetogo.io/how-to-convert-date-to-mysql-format-YYYY-MM-DD-in-javascript/)

**Comment by jadjoubran** [comment]
🎬 

- [How to get current short day name in JavaScript](https://codetogo.io/how-to-get-current-short-day-name-in-javascript/)
- [How to get current short month name in JavaScript](https://codetogo.io/how-to-get-current-short-month-name-in-javascript/)
- [How to get current year in JavaScript](https://codetogo.io/how-to-get-current-year-in-javascript/)
