### ISSUE TITLE
Use case suggestion: Setting and getting params in a URL

### ISSUE THREAD

**Issue by kakadiadarpan** [jadjoubran/codetogo.io#92]
```javascript
const url = new URL("https://kakadiadarpan.com?hello=world");
console.log(url.searchParams.get("hello"));
// "world"
url.searchParams.set("query", "params");
console.log(url.href);
// "https://kakadiadarpan.com?hello=world&query=params"

```

**Comment by jadjoubran** [comment]
This is awesome! Thanks @kakadiadarpan 
We should also a use case on how to parse query string parameters:
`new URL(document.location)` etc..
I'll continue the discussion on the PR

**Comment by jadjoubran** [comment]
🎬
- [How to set url search params in JavaScript](https://codetogo.io/how-to-set-url-search-params-in-javascript/)
- [How to get url search params in JavaScript](https://codetogo.io/how-to-get-url-search-params-in-javascript/)

Thanks @kakadiadarpan!
